### ISSUE TITLE
Document about how to use this library? 

### ISSUE THREAD

**Issue by vincentlauvlwj** [mattisonchao/ktorm-generator#1]
Seems this is a library that can auto generate some boilerplate code for [Ktorm](https://github.com/vincentlauvlwj/Ktorm)? Could you please update the README file, briefly introduce how people can use it?

**Comment by mattisonchao** [comment]
Sorry, this is just a simple generator, I will continue to complete. If something offends, I can change the project name.

**Comment by vincentlauvlwj** [comment]
Never mind, I just thought it would be better if it could be opened up for people to use.
